const NS = '@app/story';

export const FETCH_TOP_STORIES_REQUEST = `${NS}/FETCH_TOP_STORIES_REQUEST`;
export const FETCH_TOP_STORIES_SUCCESS = `${NS}/FETCH_TOP_STORIES_SUCCESS`;
export const FETCH_TOP_STORIES_FAILURE = `${NS}/FETCH_TOP_STORIES_FAILURE`;

export const FETCH_STORIES_REQUEST = `${NS}/FETCH_STORIES_REQUEST`;
export const FETCH_STORIES_SUCCESS = `${NS}/FETCH_STORIES_SUCCESS`;
export const FETCH_STORIES_FAILURE = `${NS}/FETCH_STORIES_FAILURE`;
